### ISSUE TITLE
Version information?

### ISSUE THREAD

**Issue by bclement-ocp** [balsoft/opam-nix#42]
**Is your feature request related to a problem? Please describe.**

When building a package from a git repository using `opam-nix`, the `Build_info.V1.version ()` from `dune-build-info` is always `None`.
Moreover, `dune subst` does not seem to be properly run, because I still get the `%%VERSION_NUM%%` placeholder in the resulting binary (even though the `.opam` file specifies `dune subst`).

**Describe the solution you'd like**

`Build_info.V1.version ()` should return the appropriate version, and the `dune subst` placeholders should be replaced with the appropriate values when building using `opam-nix`.

Note: if I am missing something and this should work, please do tell — I am fairly new to nix and opam-nix and just used the auto-generated `flake.nix`.

See this repo: [bclement-ocp/opam-nix-dune-build-info](https://github.com/bclement-ocp/opam-nix-dune-build-info)

Building with opam:

```
$ opam install .
# ...
$ opam-nix-dune-build-info 
dune-build-info: ddfc70d
dune subst: ddfc70d
```

Buliding with opam-nix:

```
$ nix build
# ...
$ ./result/bin/opam-nix-dune-build-info 
dune-build-info: <no version>
dune subst: %%VERSION_NUM%%
```

**Comment by balsoft** [comment]
Both of your problems are because of the way Nix handles git repositories, and is not specific to `opam-nix`. Nix strips out the `.git` subdirectory for reproducibility, therefore dune can't know the revision or other version information.

> When building a package from a git repository using opam-nix, the Build_info.V1.version () from dune-build-info is always None.

This is because there's no git repo, so `dune-build-info` can't get the commit info.

>  Moreover, dune subst does not seem to be properly run, because I still get the %%VERSION_NUM%% placeholder in the resulting binary (even though the .opam file specifies dune subst).

This is also a [documented](https://dune.readthedocs.io/en/stable/usage.html#dune-subst) feature:

> If no VCS is detected, dune subst will do nothing.

If you want to get version information into your build, you will have to pass it yourself. Nix flakes provide you with `inputs.self.sourceInfo.rev` which you can then pass to the build process somehow. A dumb solution that solves the first problem is as follows:

```nix
{
  inputs = {
    opam-nix.url = "github:tweag/opam-nix";
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.follows = "opam-nix/nixpkgs";
  };
  outputs = { self, flake-utils, opam-nix, nixpkgs }@inputs:
    # Don't forget to put the package name instead of `throw':
    let package = "opam-nix-dune-build-info";
    in flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        on = opam-nix.lib.${system};
        scope =
          on.buildOpamProject { } package ./. { ocaml-base-compiler = "*"; };

        fakeGit = pkgs.writeShellScriptBin "git" ''
          echo "$@" >& 2
          if [[ $1 == ls-tree ]]; then
            ls --zero
          elif [[ $1 == describe ]]; then
            echo ${self.sourceInfo.shortRev or "dirty"}
          fi
        '';

        overlay = final: prev: {
          # Your overrides go here
          ${package} = prev.${package}.overrideAttrs (oa: {
            nativeBuildInputs = oa.nativeBuildInputs ++ [ fakeGit ];
            preBuild = ''
              mkdir .git
            '';
          });
        };
      in {
        legacyPackages = scope.overrideScope' overlay;

        packages.default = self.legacyPackages.${system}.${package};
      });
}
```

Now,

```
❯ nix run
dune-build-info: 30e469a
dune subst: %%VERSION_NUM%%
```

I'm not sure how to convince `dune subst` to work, and as such leave it as an exercise to the reader :)

Also, if you come up with a nicer solution to this, I would be happy to document it.

**Comment by bclement-ocp** [comment]
Ah, yeah, if nix strips the `.git` directory that won't ever work. Looks like flakes are too strict in their definition of purity yet again. I wish I could have more info than the current commit, but I'll manage with this. Thanks for the quick response and your proposed solution, I'll report back if I find a nicer solution.

**Comment by balsoft** [comment]
Can we close this for now?

**Comment by bclement-ocp** [comment]
Sure
